#!/bin/bash

#@todo: add detection
DOSETUP=${1}

source ipmi_config.cfg

NETFN=0x30
CMD=0x00

I2C_BUS=0x02
I2C_SLAVE=0x4B

ADDR_MAP=0x90
ADDR_UPDATE=0x80
ADDR_SELECT=0x81
ADDR_OUTPUT_ENABLE=0x20
OUTPUT_ENABLE=0x30
OUTPUT_DISABLE=0x00

ADDR_CURRENT_MAP=0xB0

#OUTPUT_MAP="0xef 0xcd 0x8D 0x88 0x88 0xdd 0xdd 0x01"
OUTPUT_MAP="0xef 0xcd 0x8D 0xdd 0xdd 0xdd 0xdd 0x01"
ENABLE_MAP="${OUTPUT_DISABLE} ${OUTPUT_DISABLE} ${OUTPUT_DISABLE} ${OUTPUT_DISABLE} \
            ${OUTPUT_ENABLE}  ${OUTPUT_ENABLE}  ${OUTPUT_ENABLE}  ${OUTPUT_ENABLE} \
            ${OUTPUT_ENABLE}  ${OUTPUT_ENABLE}  ${OUTPUT_ENABLE}  ${OUTPUT_ENABLE} \
            ${OUTPUT_DISABLE} ${OUTPUT_DISABLE} ${OUTPUT_ENABLE}  ${OUTPUT_ENABLE}"


if [ ${DOSETUP} -eq 1 ]; then

${IPMI_CMD} ${NETFN} ${CMD} ${I2C_BUS} ${I2C_SLAVE} 9 0 ${ADDR_MAP} ${OUTPUT_MAP}
${IPMI_CMD} ${NETFN} ${CMD} ${I2C_BUS} ${I2C_SLAVE} 2 0 ${ADDR_SELECT} 0x00
#${IPMI_CMD} ${NETFN} ${CMD} ${I2C_BUS} ${I2C_SLAVE} 2 0 ${ADDR_UPDATE} 0x01

${IPMI_CMD} ${NETFN} ${CMD} ${I2C_BUS} ${I2C_SLAVE} 17 0 ${ADDR_OUTPUT_ENABLE} ${ENABLE_MAP}
fi

${IPMI_CMD} ${NETFN} ${CMD} ${I2C_BUS} ${I2C_SLAVE} 1 8 ${ADDR_MAP}
${IPMI_CMD} ${NETFN} ${CMD} ${I2C_BUS} ${I2C_SLAVE} 1 8 ${ADDR_CURRENT_MAP}
${IPMI_CMD} ${NETFN} ${CMD} ${I2C_BUS} ${I2C_SLAVE} 1 16 ${ADDR_OUTPUT_ENABLE}
